# Generated by Django 2.1.5 on 2022-08-01 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220801_2119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile1',
            new_name='Profile',
        ),
    ]
